### ISSUE TITLE
Invoke-WebRequest : { "statusCode": 404, "message": "Resource not found" }

### ISSUE THREAD

**Issue by SGromov** [Microsoft/PartnerCenterPowerShellModule#14]
Hello!
After successful command  "Add-PCAuthentication -cspappID APP ID -cspDomain FULL DOMAIN -credential $credentials"
Trying to delete a customer from sand box and having error:
PS C:\Windows\system32> $customer = Get-PCCustomer -tenantid Account MS ID
PS C:\Windows\system32> Remove-PCCustomer -tenantid $customer.id
Invoke-RestMethod : { "statusCode": 404, "message": "Resource not found" }
C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.8\src\PartnerCenterCustomer.psm1:205 знак:17
+ ... $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentTyp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Невозможно вызвать метод для выражения со значением NULL.
C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.8\src\PartnerCenterCustomer.psm1:206 знак:5
+     $obj += $response.Substring(1) | ConvertFrom-Json
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by nogreco** [comment]
Hi, sorry for late answer. I tried it and it works on  my side. Can you please try again?

**Comment by SGromov** [comment]
I tried again and : 
Remove-PCCustomer -tenantid $customer.id
Invoke-RestMethod : {"code":3000,"description":"Customer has already been deleted from the sandbox integration account","data":[],"source":"PartnerFD"}
C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.9\src\PartnerCenterCustomer.psm1:205 знак:17
+ ... $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentTyp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Невозможно вызвать метод для выражения со значением NULL.
C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.9\src\PartnerCenterCustomer.psm1:206 знак:5
+     $obj += $response.Substring(1) | ConvertFrom-Json
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
But it still presents in sand box.

**Comment by hsbsandrecv** [comment]
Even though this is not a PC SDK forum, this is the exact same behavior that I get from PC SDK Sample 1.5.0
Deleting customer.

Partner Exception:
Error Category: NotFound
Service Error Payload:
Error code: 3000
Error message: Customer has already been deleted from the sandbox integration account
Error data:

**Comment by PauloRamosGit** [comment]
I had this error in the past also when using the PC API directly. You need to open a support case to solve it.
