### ISSUE TITLE
Get-PCCustomerUsageSummary is not recognized

### ISSUE THREAD

**Issue by asensionacher** [Microsoft/PartnerCenterPowerShellModule#15]
When I try to execute Get-PCCustomerUsageSummary, it says that is not recognized after install the module.

**Comment by PauloRamosGit** [comment]
Hi @asensionacher , thanks for reporting the issue. We just found the problem and will update asap.

**Comment by PauloRamosGit** [comment]
Solved

**Comment by asensionacher** [comment]
many thanks
