### ISSUE TITLE
Get-PCUsage: More than one page

### ISSUE THREAD

**Issue by asensionacher** [Microsoft/PartnerCenterPowerShellModule#18]
Hi,

How to get the other pages when using Get-PCUsage? I mean, get more lines than the first "size" elements?

**Comment by nogreco** [comment]
Hi, have you tried to specify starttime and endtime or enlarge the 'size' paramenter? This is the referral to the REST API used: https://msdn.microsoft.com/en-us/library/partnercenter/mt791774.aspx and this is the referral to the cmdlet usage: https://github.com/Microsoft/PartnerCenterPowerShellModule/blob/master/CmdletHelp/Get-PCUsage.md

**Comment by MWL88** [comment]
I too have encountered this issue.

Specifying a larger value for the ‘size’ parameter allows you to retrieve up to 1000 items. Specifying a narrow date range does provide a way of working around the issue but it is not a solution to the issue, especially when retrieving usage data for a busy subscription with many thousands of usage records.

The REST API documentation, at the link provided by @nogreco (https://msdn.microsoft.com/en-us/library/partnercenter/mt791774.aspx), describes to how to retrieve multiple pages of results by using the continuation URIs included in the response data. Unfortunately the Get-PCUsage function discards continuation URIs.

I have implemented the paging functionality in my own fork to meet my requirements. I’ll create a PR with my updates and look forward to your feedback.
