### ISSUE TITLE
Add-PCAuthentication does not support MFA

### ISSUE THREAD

**Issue by f-bader** [Microsoft/PartnerCenterPowerShellModule#21]
If you enforce MFA for your global admins it is not possible to use the "Add-PCAuthentication" cmdlet anymore.
`Add-PCAuthentication -credential $credentials -cspAppID $cspAppId -cspDomain $cspDomain`

> Invoke-RestMethod : {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'SampleBECApp'.
Trace ID: 0000000-8d4b-46b0-a11e-0e170c6d0c00
Correlation ID: 0000000-f5f8-49fa-86fa-f63ee89c1cb8
Timestamp: 2017-08-16 07:54:11Z",
"error_codes":[50076],
"timestamp":"2017-08-16 07:54:11Z",
"trace_id":"0000000-8d4b-46b0-a11e-0e170c6d0c00",
"correlation_id":"0000000-f5f8-49fa-86fa-f63ee89c1cb8"}

As https://blogs.msdn.microsoft.com/wushuai/2016/09/25/resource-owner-password-credentials-grant-in-azure-ad-oauth/ states this seems to be a problem with the use of `grant_type=password`

> Furthermore, notice that resource owner password grant doesn't provide consent and doesn't support MFA either. So, try to use Authorization Code flow if possible and do not abuse the resource owner password grant.

**Comment by nogreco** [comment]
Have you tried to use cspClientSecret instead? 
Add-PCAuthentication -cspAppID <xxxx> -cspDomain <xxx>.onmicrosoft.com -cspClientSecret <securestring>

**Comment by toddysm** [comment]
@nogreco How do we obtain the -cspClientSecret - native apps do not have a secret in Azure AD. What secret should we use?

**Comment by toddysm** [comment]
@nogreco and @f-bader There was a bug with App ID and App Secret for which I submitted PR #38. In addition, the documentation is confusing saying that you require native app but it should be web app. Tested the fix and it works.
