### ISSUE TITLE
Azure Automation: Sequence contains more than one element

### ISSUE THREAD

**Issue by CStahlberg** [Microsoft/PartnerCenterPowerShellModule#22]
When trying to import this module to my azure Automation Account I get the following error:

`Error importing the module PartnerCenterModule. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: While importing the module, an error occurred while processing the module content. Internal error message: Sequence contains more than one element.`

I tried importing multiple times but the error still persists.

**Comment by PauloRamosGit** [comment]
Can you check if you have any PartnerCenterModule folder under C:\Program Files\WindowsPowerShell\Modules?
If yes, please delete the PartnerCenterModule folder and import it again.

**Comment by CStahlberg** [comment]
Hi Paulo,

I am not sure I understand what you mean because I am trying to add it to an Azure Automation account so that I can run reporting in a job. The azure Portal does not use my local drive as far as I know
![moduleimport](https://user-images.githubusercontent.com/24523191/29557925-d8009772-872a-11e7-93c3-0371fa53df04.JPG)
![importmodulefailure](https://user-images.githubusercontent.com/24523191/29557965-fe813a78-872a-11e7-805e-edf22b964f61.JPG)

**Comment by PauloRamosGit** [comment]
Hi @CStahlberg , I was completely outside of the point. Sorry about that.

We'll take a look and try to find a solution for this error

**Comment by InterceptBV** [comment]
Hello Paulo,

I was wondering if you have an update regarding this issue? We are also trying to add this module to an Azure Automation account and receive the exact same error message;

We tried to import the module from the marketplace and via the upload option. Both result in the following error message;
Error importing the module PartnerCenterModule. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: While importing the module, an error occurred while processing the module content. Internal error message: Sequence contains more than one element.

**Comment by nogreco** [comment]
Hi, I'm working on this issue. I'll post the update asap.

**Comment by nogreco** [comment]
hi, as promised, I've released version 0.9.0.10. With this new version you're able to import the module in Azure Automation Account:
<img width="1016" alt="pcmod" src="https://user-images.githubusercontent.com/16100184/30275453-abf4400c-9701-11e7-9698-569dca9eefbf.png">

**Comment by InterceptBV** [comment]
Thank you for the quick response, the problem has been resolved!
