### ISSUE TITLE
Incorrect module version message

### ISSUE THREAD

**Issue by MWL88** [Microsoft/PartnerCenterPowerShellModule#30]
I am using version 0.9.0.10 of the Partner Center PowerShell modules. When I execute the Add-PCAuthentication function I see the message 'A new Partner Center PowerShell Module version (0.9.0.9) is available' which is incorrect as I am using a newer version.

This message is produced by the Update-ModuleTelemetry function based on version information obtained from the module and compared against data obtained from https://api.migaz.tools/v1/version/PCPSModule.

There are 2 issues I can see:
 - The version comparison is a 'not equal' comparison and should be a 'less than' comparison
 - The version data supplied from https://api.migaz.tools/v1/version/PCPSModule is not correct, assuming is should be providing the latest available version.

**Comment by PauloRamosGit** [comment]
solved!
