### ISSUE TITLE
Can't get tue resourceUri when using Get-PCUsage

### ISSUE THREAD

**Issue by yoshimasak** [Microsoft/PartnerCenterPowerShellModule#34]
Can we get the “instanceData” property ,which the resourceUri information includes, using the Get-PCUsage cmdlt ?

When we use the utilization API (REST API), we can get it.

Get a customer's utilization records for Azure
https://msdn.microsoft.com/en-us/library/partnercenter/mt791774.aspx

However, when we use Get-PCUsage cmdlt, the "instanceData" property is lacking.

**Comment by joelst** [comment]
This does appear in the latest version for most of the resources. Is there a specific resource type that you aren't seeing show up?

**Comment by isaiahwilliams** [comment]
Hi @yoshimasak, I am going to close this issue due to inactivity. Please feel free to reopen it or create new issue if you need any help.
