### ISSUE TITLE
Define Billing Cycle

### ISSUE THREAD

**Issue by allanzh** [Microsoft/PartnerCenterPowerShellModule#35]
How can I define the Billing Cycle to an order using PowerShell Module ?

**Comment by PauloRamosGit** [comment]
Hi @allanzh , that feature is still not implemented. We encourage the community to submit that update

**Comment by allanzh** [comment]
Hi @PauloRamosGit .
I'm gonna use Partner Center C# API to make things work here.
Thanks.
