### ISSUE TITLE
Does not seem to pickup all users of a given customer

### ISSUE THREAD

**Issue by ManuInNZ** [Microsoft/PartnerCenterPowerShellModule#40]
# Get all customer users
$users = Get-PCCustomerUser -tenantid $customer.id -all

$users | ? { $_.lastName -contains 'theta'}
--> Returns nothing although 2 users exist.
![2018-01-24 14_22_50-microsoft edge](https://user-images.githubusercontent.com/7937408/35309609-3d29671c-0112-11e8-85fb-687a2da40560.png)

using latest to date
Get-InstalledModule -Name PartnerCenterModule

Version    Name                                Repository           Description                                                                                                               
-------    ----                                ----------           -----------                                                                                                               
0.9.0.14   PartnerCenterModule                 PSGallery            Partner Center Powershell Module (preview)

**Comment by PauloRamosGit** [comment]
Hi @ManuInNZ ,
Can you try $users | ? { $_.lastName -Like '*theta*'}

**Comment by ManuInNZ** [comment]
I have checked manually the list using out-gridview and I can confirm the
users are present in the array of users.

Cheers
Manu
