### ISSUE TITLE
No Paging with Get-PCInvoiceLineItems

### ISSUE THREAD

**Issue by dennings** [Microsoft/PartnerCenterPowerShellModule#41]
With that cmd-let i can just grab the first 2000 lines of items, because there is no paging ;(

i take that command:
Get-PCInvoiceLineItems -invoiceid $lastinvioce.id -billingprovider Azure -invoicelineitemtype UsageLineItems -size 2000

Can someone implement paging like in PCUsage2 ????

**Comment by dennings** [comment]
i have the Solution here, can please someone check that in?

--
function Get-PCInvoiceLineItems
{
  [CmdletBinding()]

  Param(
    [Parameter(Mandatory = $true)][String]$invoiceid,
    [Parameter(Mandatory = $true)][ValidateSet("Azure","Office")][string]$billingprovider,
    [Parameter(Mandatory = $true)][ValidateSet("BillingLineItems","UsageLineItems")][string]$invoicelineitemtype,
    [Parameter(Mandatory = $false)][int]$size = 200,
    [Parameter(Mandatory = $false)][int]$offset = 0,
    [Parameter(Mandatory = $false)][string]$satoken = $GlobalToken
  )
  _testTokenContext($satoken)
  Send-ModuleTelemetry -functionName $MyInvocation.MyCommand.Name
  $obj = @()
  $url = "https://api.partnercenter.microsoft.com/v1/invoices/{0}/lineitems/{1}/{2}?size={3}&offset={4}" -f $invoiceid,$billingprovider,$invoicelineitemtype,$size,$offset

  $headers = @{Authorization="Bearer $satoken"}

  $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentType "application/json" -Method "GET" #-Debug -Verbose
  $obj += $response
  return (_formatResult -obj $obj -type "Invoice") 
}
--

**Comment by PauloRamosGit** [comment]
Thank you @dennings . Code included on PR #43
