### ISSUE TITLE
Get Invoice by ID not working

### ISSUE THREAD

**Issue by dennings** [Microsoft/PartnerCenterPowerShellModule#42]
Hi, 
i do the following to retrieve the PDF download link:
Get-PCInvoice -invoiceid D030001QMU -Verbose

OUTPUT:
VERBOSE: GET https://api.partnercenter.microsoft.com/v1/invoices/D030001QMU with 0
-byte payload
Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.15\Partne
rCenterInvoice.psm1:46 char:21

but the Invoice is corret and i got it with the "-all" Parameter ;(

**Comment by joelst** [comment]
I have not been able to repro this issue. Were you able to figure out what was happening?

**Comment by joelst** [comment]
@dennings You were probably using App authentication. You must use App+User authentication for Invoice and User tasks. We will add checking for this in a future release.

**Comment by isaiahwilliams** [comment]
Hi @dennings please free to reopen this issue if you are still having issues.
