### ISSUE TITLE
Please provide functionality to create Native Application ID for CSP account

### ISSUE THREAD

**Issue by cpatel27** [Microsoft/PartnerCenterPowerShellModule#45]
As part of an automation workflow, we would like to setup a third party application. This requires us to create a Native Application ID programmatically via PowerShell. We could not find a way to this with the PartnerCenterPowerShell Module.

**Comment by isaiahwilliams** [comment]
Hi @cpatel27, you can utilize the Azure Active Directory PowerShell module to create an application. If you are interested you can find complete details [here](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadapplication?view=azureadps-2.0). Right now there are no plans to introduce this functionality into this module. I would like to encourage you to utilize the Azure AD modules.
