### ISSUE TITLE
View Service Requests in new Service Request Feature in Portal

### ISSUE THREAD

**Issue by apearcebfc** [Microsoft/PartnerCenterPowerShellModule#46]
I have two tenants that are both CSP/Admin. 

When i log a service request one is done using the new method (side window in the customers Office Portal).  The other is done the old way.

When using get-pscr, for the old tenant i see the service request however when i use it for the other tenant (with the correct tenant ID), i dont see them.  Is there a reason why?

Thanks

Alex

**Comment by isaiahwilliams** [comment]
Hi @Alex, there have been a number of update to Partner Center and this module. Can you confirm that you are still encountering this issue?

**Comment by isaiahwilliams** [comment]
Hi @apearcebfc please feel free to reopen this issue if you are still having issues.
