### ISSUE TITLE
new-pcsr - Can you create a service request in a customers tenant?

### ISSUE THREAD

**Issue by apearcebfc** [Microsoft/PartnerCenterPowerShellModule#47]
I need to be able to submit a request into the customer tenant.  I'm almost expecting a new-pcsr -tenantID but i dont see anything.  anything you can help with?

thanks

A.

**Comment by PauloRamosGit** [comment]
Hi @apearcebfc ,
This powershell module supports only what is provided by PartnerCenterAPI. What specific request are you searching for?

**Comment by apearcebfc** [comment]
Hey @PauloRamosGit  Thanks for the reply.  We want to be able to have calls logged in our system because of CSP but then when we need to escalate to MS, we can easily do that by clicking a button so we can put it in a queue and then upload via powershell or via the API.  Don't care how, just want a better automation system :-)

**Comment by PauloRamosGit** [comment]
PartnerCenter API supports only open Partner Center support tickets (https://docs.microsoft.com/en-us/partner-center/develop/create-a-service-request-)
I think you need to refer to specific O365 or Azure APIs to make specific service support requests.

**Comment by apearcebfc** [comment]
Understand what you are saying but at the moment you have to go through the Partner Centre to go into the customer tenant to log a call so I feel it should be part of that API :-)
