### ISSUE TITLE
Web app / API required permissions issue

### ISSUE THREAD

**Issue by JimBobUKII** [Microsoft/PartnerCenterPowerShellModule#48]
I thought I would do a little testing to see if I could get the reports in needed but came across some issues, its more than likely my set up but here we go
Testing against PC Sandbox

```
$clientSecret = '...............'
$clientSecretSecure = $clientSecret | ConvertTo-SecureString -AsPlainText -Force

Add-PCAuthentication -cspappID '.....................' -cspDomain 'sandbox.onmicrosoft.com' -cspClientSecret $clientSecretSecure
```

First tests work no problem
```
$PCCustomers = Get-PCCustomer -all
$PCCustomers.companyProfile | sort companyName
```

if i try the following command, I get an error

```
Get-PCCustomerLicensesDeployment -tenantid $customer.id

Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
...
```

There are other commands that I cannot use too so I guess this is a permission for web app / api?

Could some one tell me what exact permissions are required please

Thanks in advance

**Comment by JimBobUKII** [comment]
Anyone?

**Comment by MortenRei** [comment]
I have the exact same issue. 

Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.17\PartnerCenterProfiles.psm1:351 char:17
+ ... $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentTyp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.17\PartnerCenterProfiles.psm1:352 char:5
+     $obj += $response.Substring(1) | ConvertFrom-Json
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by PauloRamosGit** [comment]
Hi @JimBobUKII and @MortenRei ,
There is a large number of methods that can only be called using NativeAppId+User+Pass. This is a PartnerCenterAPI requirement, not something we enforce on powershell module side.

$credential = Get-Credential

Add-PCAuthentication -cspappID '<native app id GUID>' -cspDomain '<csp partner domain>' -credential $credential

**Comment by MortenRei** [comment]
I actually found the fault for this error, and it's almost unbelievable.. 
Try to set a much easier password on the account your authenticating with, and don't use any special chars to begin with. See if that does solve your problem. If yes, experiment with creating more robust passwords.
