### ISSUE TITLE
Get-PCSubscription: offer ID is empty/null

### ISSUE THREAD

**Issue by Popsikill** [Microsoft/PartnerCenterPowerShellModule#49]
Strangely - sometimes when we use this command Offer ID is sometimes null - is this normal?
Would you ever get a subscription that didn't have an offer applied?

**Comment by isaiahwilliams** [comment]
Hi @Popsikill, this command should always return the offer identifier. There have been a handful of update since this issue has been opened. Can you confirm you are still encountering this inconsistent behavior?

**Comment by isaiahwilliams** [comment]
Hi @Popsikill, please feel free to reopen the close if you are still having issues.
