### ISSUE TITLE
The identity of the calling application could not be established

### ISSUE THREAD

**Issue by wgbartley** [Microsoft/PartnerCenterPowerShellModule#52]
Hello!

I am trying to use `Get-PCCustomer -all` but am receiving errors.  My script is:

```
$VerbosePreference = "continue"

$clientSecret = "..."
$clientSecretSecure = $clientSecret | ConvertTo-SecureString -AsPlainText -Force

$credentials = Get-Credential "..."

# Native app authentication
Add-PCAuthentication -cspappID "..." -cspDomain "..." -credential $credentials

# Web app authentication
#Add-PCAuthentication -cspappID "..." -cspDomain "..." -cspClientSecret $clientSecretSecure

Get-PCCustomer -all
```

The `...` are populated with values from the Partner Center web app and/or native app registrations.

When I try to run the script with the native app authentication line un-commented, I see:
```
VERBOSE: POST https://login.windows.net/office.smartechcorp.net/oauth2/token with -1-byte payload
VERBOSE: received 3429-byte response of content type application/json; charset=utf-8
VERBOSE: POST https://api.partnercenter.microsoft.com/generatetoken with -1-byte payload
VERBOSE: received 4422-byte response of content type application/json;charset=UTF-8
VERBOSE: GET https://api.migaz.tools/v1/version/PCPSModule with 0-byte payload
VERBOSE: received 10-byte response of content type application/json; charset=utf-8
A new Partner Center PowerShell Module version (0.9.0.17) is available
VERBOSE: POST https://api.migaz.tools/v1/telemetry/PCPSModule with -1-byte payload
VERBOSE: received 4-byte response of content type application/json; charset=utf-8

Name                           Value
----                           -----
Username                       user@host.com
Domain                         my.domain.com
Resource                       https://api.partnercenter.microsoft.com
ClientId                       some-client-id-guid
VERBOSE: POST https://api.migaz.tools/v1/telemetry/PCPSModule with -1-byte payload
VERBOSE: received 4-byte response of content type application/json; charset=utf-8
VERBOSE: GET https://api.partnercenter.microsoft.com/v1/customers with 0-byte payload
Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.16\PartnerCenterCustomer.psm1:36 char:21
+ ... $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentTyp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.16\PartnerCenterCustomer.psm1:37 char:9
+         $obj += $response.Substring(1) | ConvertFrom-Json
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

And when I try using web app authentication, I see:

```
VERBOSE: POST https://login.windows.net/office.smartechcorp.net/oauth2/token with -1-byte payload
VERBOSE: received 1241-byte response of content type application/json; charset=utf-8
VERBOSE: POST https://api.partnercenter.microsoft.com/generatetoken with -1-byte payload
VERBOSE: received 2986-byte response of content type application/json;charset=UTF-8
VERBOSE: GET https://api.migaz.tools/v1/version/PCPSModule with 0-byte payload
VERBOSE: received 10-byte response of content type application/json; charset=utf-8
A new Partner Center PowerShell Module version (0.9.0.17) is available
VERBOSE: POST https://api.migaz.tools/v1/telemetry/PCPSModule with -1-byte payload
VERBOSE: received 4-byte response of content type application/json; charset=utf-8

Name                           Value
----                           -----
Domain                         my.domain.com
Resource                       https://graph.windows.net
ClientId                       some-client-id-guid
VERBOSE: POST https://api.migaz.tools/v1/telemetry/PCPSModule with -1-byte payload
VERBOSE: received 4-byte response of content type application/json; charset=utf-8
VERBOSE: GET https://api.partnercenter.microsoft.com/v1/customers with 0-byte payload
Invoke-RestMethod : {"code":0,"description":"The identity of the calling application could not be established.","data":[],"source":"PartnerFD"}
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.16\PartnerCenterCustomer.psm1:36 char:21
+ ... $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentTyp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.16\PartnerCenterCustomer.psm1:37 char:9
+         $obj += $response.Substring(1) | ConvertFrom-Json
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

I have created the native app registration in Azure AD with the following delegated permissions:
 - Windows Azure Active Directory
   - Access the directory as the signed-in user
   - Read all users' basic profiles
   - Sign in and read user profile
 - Microsoft Partner Center (SampleBECApp)
   - Access Partner Center

The app is registered in Partner Center as a native app using the "Register existing app" link and selected the app that was registered in Azure AD.

The user account I am using is a global admin in both Partner Center and Azure AD.

Also, despite the `A new Partner Center PowerShell Module version (0.9.0.17) is available` notice, I have made sure module is updated to 0.9.0.17 with `Get-Module -Name "PartnerCenterModule"`:
```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.9.0.16   PartnerCenterModule                 {Add-PCAuthentication, Add-PCCustomerRoleMember, Get-PCAddressRulesByMarket, Get-PCAuditRecords...}
```

I've been at this for several days, and this is the farthest I've been able to get.  Any help would be greatly appreciated!  Let me know if I left anything out that may help in debugging.

Thank you!

**Comment by cblackuk** [comment]
Hi @wgbartley 
Not sure what your particular problem is but your module is outdated so I would suggest you try this:
PS C:\> Get-Module -Name "PartnerCenterModule"
PS C:\> Install-Module PartnerCenterModule
WARNING: Version '0.9.0.16' of module 'PartnerCenterModule' is already installed at 'C:\Program
Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.16'. To install version '0.9.0.17', run Install-Module and
add the -Force parameter, this command will install version '0.9.0.17' in side-by-side with version '0.9.0.16'.
PS C:\> Install-Module PartnerCenterModule -force
PS C:\> Get-Module -Name "PartnerCenterModule"
PS C:\> Import-Module PartnerCenterModule
PS C:\> Get-Module -Name "PartnerCenterModule"

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.9.0.17   PartnerCenterModule                 {Add-PCAuthentication, Add-PCCustomerRoleMember, Get-PCAdd...

Then retry your script.

**Comment by wgbartley** [comment]
@cblackuk - It looks like I forgot to restart PowerShell ISE when I updated the module in a separate PowerShell console.  The good news is that it's definitely using `0.9.0.17` now  :-).  The bad news is the error messages are still the same :-(.

**Comment by cblackuk** [comment]
@wgbartley I cannot test this particular cmdlet at the moment, might try tomorrow from work but first error looks like Authentication issue as 403 the second one; however, looks like something is wrong in the PartnerCenterCustomer.psm1:36 char:21 which is not something I was looking at... so it would require debugging again ;-(

**Comment by PauloRamosGit** [comment]
$clientSecret = 'webapp secret'
$clientSecretSecure = $clientSecret | ConvertTo-SecureString -AsPlainText -Force
Add-PCAuthentication -cspDomain 'mydomain.onmicrosoft.com' -cspAppID 'webapp id' -cspClientSecret $clientSecretSecure

$customer = Get-PCCustomer -all | Out-GridView -PassThru

I've just tried on my env and it worked without issues. Can you double check appid and appsecret, or create a new one for test?

**Comment by wgbartley** [comment]
@PauloRamosGit - Thanks for looking into this!

I tried generating a new web app keys (a 1-year key and a 2-year key) with the same results:

```
{"code":0,"description":"The identity of the calling application could not be established.","data":[],"source":"PartnerFD"}
```

I noticed that your sample `cspDomain` is `mydomain.onmicrosoft.com`.  Should my domain also end in `onmicrosoft.com`?  I've copied+pasted the domain from the Partner Center web app registration for `cspDomain`.  I have tried our `onmicrosoft.com` domain but receive:

```
{"error":"unauthorized_client","error_description":"AADSTS70001: Application with identifier '...' was not found in the directory 
....onmicrosoft.com ...
```

**Comment by PauloRamosGit** [comment]
Found the reason for your problem @wgbartley 

Go to the User management on Partner Center, select the user you are using on the script, enable Assists your customers as: Admin Agent.

**Comment by wgbartley** [comment]
@PauloRamosGit - I made the admin agent change and waited about 45 minutes, but I am still getting the same error.

**Comment by PauloRamosGit** [comment]
If:
. You are using Native App Id
. Right domain name
. Right username and password
. User have the right permissions
. You are using NativeApp Id + Credentials authentication
i don't see why you are getting this error

**Comment by wgbartley** [comment]
Just an update that I spoke with Partner Center support yesterday.  They weren't able to find any issues with the account, but they also weren't able to support the Power Shell module either.  Back to the drawing board!

**Comment by PauloRamosGit** [comment]
> I tried generating a new web app keys (a 1-year key and a 2-year key) with the same results:

If you are creating keys, that means you are creating a Web App.

Please create a Native App and use NativeApp Id + Credentials authentication

**Comment by PauloRamosGit** [comment]
Hi @wgbartley , have you solved the problem?

**Comment by wgbartley** [comment]
I am still experiencing the problem with the PowerShell module.  However, I went ahead and used the C# SDK and was able to get the data I was after.

Even though I'm using the same username and password for the C# SDK, I still get the `"The identity of the calling application could not be established."` error with the PowerShell module using the web app credentials.

The one thing I haven't tried yet is comparing the HTTP traffic between the C# SDK and PowerShell module to see if the requests are somehow different.

**Comment by isaiahwilliams** [comment]
Hi @wgbartley this error typically an indentication that the application you are using does not have a service principal. If you are still experincing this error I would recommend unregistering the application through Partner Center and then registering it again. Please let us know if you have any issues, and I will be glad to help!

**Comment by isaiahwilliams** [comment]
Hi @wgbartley, I am going to close this issue. If you are still encountering this issue please free to reopen it or create a new issue.
