### ISSUE TITLE
Error validating credentials - Cannot retrieve the token: The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by gsee2000** [Microsoft/PartnerCenterPowerShellModule#53]
Today ran

Install-Module -Name PartnerCenterModule

Step 1
App management already setup

Step 2

$credentials = Get-Credential 'username@domain.onmicrosoft.com'
Add-PCAuthentication -cspappID 'portal-generated-guid-entered' -cspDomain 'domain.onmicrosoft.com' -credential $credentials

Receiving the following:

Invoke-RestMethod : {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or
password\r\nTrace ID: 5c1fe98f-116a-4a2a-b832-28d44fcb0300\r\nCorrelation ID: f53bfd54-c805-4b27-bcd8-664faf89f556\r\nTimestamp: 2018-03-23
10:54:27Z","error_codes":[70002,50126],"timestamp":"2018-03-23
10:54:27Z","trace_id":"5c1fe98f-116a-4a2a-b832-28d44fcb0300","correlation_id":"f53bfd54-c805-4b27-bcd8-664faf89f556"}
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.17\PartnerCenterAuthentication.psm1:32 char:17
+ ... $response = Invoke-RestMethod -Uri $url -ContentType "application/x-w ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
The property 'access_token' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.17\PartnerCenterAuthentication.psm1:33 char:12
+     return $response.access_token
+            ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

The property 'Domain' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.17\PartnerCenterAuthentication.psm1:106 char:5
+     Update-ModuleTelemetry -cspDomain $result.Domain
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Invoke-RestMethod : {"Message":"An error has occurred."}
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.17\PartnerCenterTelemetry.psm1:31 char:19
+ ...   $result = Invoke-RestMethod -Method Post -Uri "https://api.migaz.to ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Cannot retrieve the token: The remote server returned an error: (401) Unauthorized.

Can confirm the username and password are correct as I am able to authenticate with the same set of creds and administer via the portal https://partnercenter.microsoft.com/ without issue.

Is anyone else encountering this issue using the latest PartnerCenterModule?

**Comment by PauloRamosGit** [comment]
Hi @gsee2000 , just tested on my side. Both authentication types are working for me.

**Comment by gsee2000** [comment]
Due to incorrect user. Although the azure global admin of the same domain has full admin rights over the CSP, and is able to authenticate into the web UI and administer CSP activities, this was unable to authenticate via powershell. Changed to the CSP admin user and was able to login. Please close.
