### ISSUE TITLE
Get-PCManagedServices / Get-PCCustomerBillingProfile throws a 403 forbidden error

### ISSUE THREAD

**Issue by bdzeeuw** [Microsoft/PartnerCenterPowerShellModule#54]
I'm using the PowerShell Module to pull (and modify) data from the Azure CSP Portal. I'm able to to authenticate successfully, using the Add-PCAuthentication cmdlets.  I'm able to retrieve a list of customers, add new customers and subscriptions. However when running commands like Get-PCManagedServices / Get-PCCustomerBillingProfile, I get the following error:

$customer = Get-PCCustomer -tenantid '<guid>'
Get-PCManagedServices -tenantid $customer.id

Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.17\PartnerCenterCustomer.psm1:222 char:17
+ ... $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentTyp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.17\PartnerCenterCustomer.psm1:223 char:5
+     $obj += $response.Substring(1) | ConvertFrom-Json
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

My CSP user has the Admin agent role  & Global admin role. Any ideas?

**Comment by johandehaan** [comment]
I had exactly the same problem. I created a Web App and tried to authenticate with a user with MFA enabled. Did not work. When I used the Native App and an Office 365 Only User (a not-dirsynced user) I could authenticate and retrieve the information. Does this help you?

**Comment by bdzeeuw** [comment]
Hi Johan,

That did the trick. Authenticating using the user authentication, rather than the app authentication. I'm now able to run the above mentioned cmdlets (and others). Thnx!

**Comment by PauloRamosGit** [comment]
Thank you @johandehaan
