### ISSUE TITLE
Error to run Get-PCAuditRecords

### ISSUE THREAD

**Issue by kevinmay** [Microsoft/PartnerCenterPowerShellModule#55]
Error to run Get-PCAuditRecords

Ex: Get-PCAuditRecords -startDate '2018-03-01' -endDate '2018-03-31'

方法引動過程失敗，因為 [System.Management.Automation.PSCustomObject] 未包含名為 'Substring' 的方法。
位於 C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.17\PartnerCenterPartner.psm1:42 字元:5
+     $obj += $response.Substring(1) | ConvertFrom-Json
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Substring:String) []，RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by PauloRamosGit** [comment]
Thank for reporting the error @kevinmay . I've just updated the code and the module on PSGallery
