### ISSUE TITLE
Remove-PCCustomer "startIndex cannot be larger than length of string"

### ISSUE THREAD

**Issue by ehrnst** [Microsoft/PartnerCenterPowerShellModule#56]
Hi,

Trying to remove customers/tenants from the sandbox using "remove-PcCustomer -tenantId <guid>" I get the following error

`Exception calling "Substring" with "1" argument(s): "startIndex cannot be larger than length of string.
Parameter name: startIndex"
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.9.0.17\PartnerCenterCustomer.psm1:206 char:5
+     $obj += $response.Substring(1) | ConvertFrom-Json
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException
`
Any Ideas?

**Comment by ehrnst** [comment]
I believe the issue is on this line https://github.com/Microsoft/PartnerCenterPowerShellModule/blob/f7208ceac615deee0ab4c2d3e0dcc304bf3cde95/PartnerCenterModule/PartnerCenterCustomer.psm1#L205

As the API it self does not return any response, hence the variable is blank

**Comment by PauloRamosGit** [comment]
Thanks for reporting @ehrnst . Updated the code accordingly to avoid the error but still returning the response exception
