### ISSUE TITLE
Get a list of products

### ISSUE THREAD

**Issue by tasgray** [Microsoft/PartnerCenterPowerShellModule#60]
Hey Team,

Would it be possible to include this method in the module? - https://docs.microsoft.com/en-us/partner-center/develop/get-a-list-of-products

**Comment by isaiahwilliams** [comment]
@tasgray we are currently working on a long term plan for this module. Thank you for bring this feedback to our attention, we will ensure that this request is incorporated into our plans. Are you looking to utilize this module to purchase Reserved Instances?

**Comment by tasgray** [comment]
@isaiahwilliams my pleasure. I am not looking to purchase Reserved Instances at this point in time.

**Comment by joelst** [comment]
This basic functionality was introduced in 0.10.0.2. 

Please try it out and give feedback. As @isaiahwilliams mentioned, we have a longer term plan to add other functionality into an upcoming release of the module. Feedback like this helps us to prioritize, so thank you for taking the time to post the request.
