### ISSUE TITLE
Regions missing from Validation for Get-PCAzureRateCard

### ISSUE THREAD

**Issue by CStahlberg** [Microsoft/PartnerCenterPowerShellModule#65]
# Steps to reproduce
`$RateCard = Get-PCAzureRateCard -currency 'EUR' -Region 'DE'`

## Expected behavior
This should give you the ratecard for the currency of euro, which it did just fine befor you added validation in version 0.10.0.0.

## Actual behavior

`Get-PCAzureRateCard : Cannot validate argument on parameter 'Currency'. The argument "EUR" does not match the 
"^(NOK|SZL|SEK|CHF|CHE|CHW|SYP|TWD|TJS|TZS|THB|USD|XOF|NZD|TOP|TTD|TND|TRY|TMT|USD|AUD|UGX|UAH|AED|GBP|USD|USD|USN|UYU|UYI|UZS|VUV|VEF|VND|USD|USD|XPF|MAD|YER|ZMW|ZWL|XBA|XBB|XBC|XBD|XTS|XXX|XAU|XPD|XPT|XAG)$" pattern. Supply an argument that matches 
"^(NOK|SZL|SEK|CHF|CHE|CHW|SYP|TWD|TJS|TZS|THB|USD|XOF|NZD|TOP|TTD|TND|TRY|TMT|USD|AUD|UGX|UAH|AED|GBP|USD|USD|USN|UYU|UYI|UZS|VUV|VEF|VND|USD|USD|XPF|MAD|YER|ZMW|ZWL|XBA|XBB|XBC|XBD|XTS|XXX|XAU|XPD|XPT|XAG)$" and try the command again.`

Did anyone actually test this? Also why is USD in there 5 times?

**Comment by isaiahwilliams** [comment]
Hi @CStahlberg, thank you for bringing this issue to our attention. We are going to investigate and review the PR that you submitted.
