### ISSUE TITLE
Ability to Remove Re-seller Relationship

### ISSUE THREAD

**Issue by cblackuk** [Microsoft/PartnerCenterPowerShellModule#70]
# Feature Request

**Is your feature request related to a problem? Please describe.**
We are trying to automate Offboarding of a customer and there is no End to End process as we cannot remove Reseller relationship. It is available via API but not cmdlet has been written.

Link to API -> https://docs.microsoft.com/en-us/partner-center/develop/remove-a-reseller-relationship-with-a-customer

**Describe the solution you would like**
New Function/Cmdlet for it to be created so it can be automated.

**Comment by joelst** [comment]
Fixed in #71
