### ISSUE TITLE
Where is Get-PCUsage2

### ISSUE THREAD

**Issue by slavizh** [Microsoft/PartnerCenterPowerShellModule#74]
# Steps to reproduce

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

Get-PCUsage2 seems to be gone. Why it was removed and what cmdlet we should use to get the full usage data for a period? There is not continuation link in Get-PCUsage

## Expected behavior

> Share the expected output

## Actual behavior

> What is the behavior observed?

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

**Comment by isaiahwilliams** [comment]
Hi @slavizh, the Get-PCUsage cmdlet has been modified so the continuation link is no longer necessary. The maximum number of records the API will return for this operation is 1000. So, we have implemented the appropriate logic to handle the request for additional records if 1000 entries is returned in a single call to the API. Are you finding that some records are missing?

**Comment by slavizh** [comment]
@isaiahwilliams  @joelst The examples and help files are not quite clear. You have -ResultSize parameter. If I am getting all the results why there is -ResultSize parameter. I want to get all the usage data without having to specify specific number in  -ResultSize or having to do something crazy like  -ResultSize 10000000 . When changes are made it is good to actually document those. Look at how AzureRM is documentation breaking changes and providing migration guide. At least provide better documentation for Get-PCUsage as it is not correct:


    -ResultSize <Int32>
        Specifies the maximum number of results to return. The default value and the maximum value is 1000. To retrieve
         more than 1000 records you must use the continuation link.

        Required?                    false
        Position?                    named
        Default value                1000
        Accept pipeline input?       false
        Accept wildcard characters?  false

**Comment by joelst** [comment]
We appreciate the feedback you have provided, we rely heavily on the community to identify issues and to submit fixes and enhancements. We understand that changes break existing scripts and implementations and we know that can be frustrating (we have been on both sides of this).

As part of our plan to get this from a pre-release (0.x) module to a 1.x release (and eventually a 2.x), we are standardizing cmdlet verbs, nouns, and parameter names, adding help information, adding validation, and trying to simplify its use for IT Pros. We are also working to add missing functionality.  

Although we wish to break as few things as possible, there are some decisions made that help get to our goal that unfortunately break things. As we do this, we will do our best to document the changes in the change log, and by updating the help documentation.

The help information you referenced, was updated almost three weeks ago (PR  #63 ) to better reflect the functionality of that cmdlet. I'm not sure which version you are using and if you pulled it from PowerShell Gallery or from GitHub. Although we may have frequent pull requests on GitHub, we try to update PowerShell Gallery only a couple times a month unless there is a critical fix that needs to be addressed.

There is still _much room for improvement_ in the documentation and everywhere else. Please keep the feedback and pull requests coming!

**Comment by slavizh** [comment]
Ok. But back on the issue. So how this cmdlet (Get-PCUsage) is now used. Do I need to use -ResultSize or it will automatically get all possible records for the time period without me specifying that parameter. Because the documentation is not updated properly (still referring to all things) I need to know how this cmdlet works without having to investigate the code.
