### ISSUE TITLE
PartnerCenterModule.psm1 contains breaking typo in class CustomerUserPasswordProfile

### ISSUE THREAD

**Issue by InterceptBV** [Microsoft/PartnerCenterPowerShellModule#78]
# Steps to reproduce

In the latest version (0.10.0.3), this class contains a typo at line 195 ad 196 which causes "New-PCCustomerUser" to not create new users:

[]
class CustomerUserPasswordProfile

{

    [string] $password

    [bool] $forceChangePassword

    CustomerUserPasswordProfile ([SecureString] $password,[bool]$forceChangePassword)

    {

        $this.password = _

        String -string $password

        $this.forceChangePassword = $forceChangePassword

    }

}
[/]

> What steps can reproduce the defect?

Update to 0.10.0.3 and execute New-PCCustomerUser

> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
A new PC Customer should be created

> Share the expected output
Error at At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.10.0.3\PartnerCenterModule.psm1:195 char:26

## Actual behavior

> What is the behavior observed?

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

**Comment by InterceptBV** [comment]
When I change the line back to this, the module works again:
$this.password = _unsecureString -string $password

**Comment by isaiahwilliams** [comment]
Hi @InterceptBV, 

This is a good catch I am working to correct the issue. After some regression testing I will publish a updated version of the module.

**Comment by isaiahwilliams** [comment]
I have addressed this issue with PR #81. Thank you for bring it to my attention.

**Comment by InterceptBV** [comment]
Hello Isaiah,

Thank you for the quick response and resolving the issue.

Kind regards,

Rinie Huijgen
CTO
Intercept
Zwolle, Zwartewaterallee 25, 8032 DZ, Tel: 038-7779 820
Email: rhuijgen@intercept.nl<mailto:rhuijgen@intercept.nl> Internet: www.intercept.nl<http://www.intercept.nl/>
Mobiel: +31 (0)6-24 997766

[cid:image002.png@01D3BB0B.878103D0]


Van: Isaiah Williams <notifications@github.com>
Verzonden: donderdag 12 juli 2018 16:44
Aan: Microsoft/PartnerCenterPowerShellModule <PartnerCenterPowerShellModule@noreply.github.com>
CC: Rinie Huijgen | Intercept <rhuijgen@intercept.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Microsoft/PartnerCenterPowerShellModule] PartnerCenterModule.psm1 contains breaking typo in class CustomerUserPasswordProfile (#78)


I have addressed this issue with PR #81<https://github.com/Microsoft/PartnerCenterPowerShellModule/pull/81>. Thank you for bring it to my attention.
