### ISSUE TITLE
New-PCCustomer returns "A property has invalid data"

### ISSUE THREAD

**Issue by PowellDean** [Microsoft/PartnerCenterPowerShellModule#82]
Hi:

Following the example from the source code itself, we have the following code:

```PowerShell
$newDefaultAddress = New-PCCustomerDefaultAddress -Country 'US' -Region 'NA' -City 'Seattle' -State 'WA' -AddressLine1 '1234 fake road' -PostalCode '98101' -FirstName 'TestFirst' -LastName 'TestLast' -PhoneNumber '20612341234'
$newBillingProfile = New-PCCustomerBillingProfile -FirstName 'TestFist' -LastName 'TestLast' -Email 'test@test.local' -Culture 'en-US' -Language 'en' -CompanyName 'TestCompany' -DefaultAddress $newDefaultAddress
$newCompanyProfile = New-PCCustomerCompanyProfile -Domain 'testsandboxt1.onmicrosoft.com'
$newCustomer = New-PCCustomer -BillingProfile $newBillingProfile -CompanyProfile $newCompanyProfile
```

Return code from Invoke-RestMethod method is:

Invoke-RestMethod : {"code":27002,"description":"A property has invalid data.","data":["property_name:  StateInvalid - Details","details:  
"],"source":"PartnerFD"}

State given is 'WA' which is a valid code and the Zip Code is a correct one for that city and state. If I do not pass in the state code, I am prompted for it.

**Comment by isaiahwilliams** [comment]
Hi Dean,

If your remove -Region 'NA' it should work. When working with addresses in the US the region parameter shoild not be used. I will add an item to our backlog to incorporate the appropriate log to provide a more meaningful error when this happens. Please let me know if you have any other issue.

Isaiah Williams

________________________________

**Comment by PowellDean** [comment]
That worked like a charm. Thanks very much. From my perspective, the issue is solved. If you need help with documentation or testing, let me know.

Dean Powell
Edmonton, Canada

**Comment by isaiahwilliams** [comment]
Hi Dean, 

I am going to close this issue because we have added logic to prevent this issue from happening with the new version of the module. We would greatly appreciate any feedback and help with documentation that you can offer. You can find the new version of the module at https://github.com/Microsoft/Partner-Center-PowerShell

**Comment by PowellDean** [comment]
Hi:

Thank you very much. I will test the new module and keep you posted. I will
be happy to help as much as I can.

Regards,
Dean Powell
Edmonton, Canada
