### ISSUE TITLE
Get-PCCustomerRelationship is broken via API or PowerShell - code 1002

### ISSUE THREAD

**Issue by cblackuk** [Microsoft/PartnerCenterPowerShellModule#83]
# Steps to reproduce

Direcrly via PowerShell:

```powershell
 Get-PCCustomerRelationship -TenantId $($CustomerDetails.id) -Verbose
VERBOSE: GET https://api.partnercenter.microsoft.com/v1/customers/c9382948-8233-4b81-89e4-8b035d0b366b/relationships with 0-byte payload
Invoke-RestMethod : {"code":1002,"description":"Authorization Failed","data":[],"source":"PartnerFD"}
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.10.0.4\PartnerCenterCustomer.psm1:513 char:17
+ ... $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentTyp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\PartnerCenterModule\0.10.0.4\PartnerCenterCustomer.psm1:514 char:5
+     $obj += $response.Substring(1) | ConvertFrom-Json
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

Directly via API by creating custom headers:

```powershell
 $url = "https://api.partnercenter.microsoft.com/v1/customers/{0}/relationships" -f $TenantId

    $headers = New-Object 'System.Collections.Generic.Dictionary[[string],[string]]'
    $headers.Add("Authorization", "Bearer $SaToken")
    $headers.Add("MS-PartnerCenter-Application", $ApplicationName)

    $obj = @()
    $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentType "application/json" -Method "GET" #-Debug -Verbose
Invoke-RestMethod : {"code":1002,"description":"Authorization Failed","data":[],"source":"PartnerFD"}
At line:8 char:17
+ ... $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentTyp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
PS C:\Users\sucblack\ukrepos\AZS_dev_black> $url
https://api.partnercenter.microsoft.com/v1/customers/c9382948-8233-4b81-89e4-8b035d0b366b/relationships
```
## Expected behavior

It should print the relationship but instead it breaks with the code above.

## Actual behavior

See error above

## Environment

```powershell
Get-Module -Name PartnerCenterModule

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.10.0.4   PartnerCenterModule                 {Add-PCAuthentication, Add-PCCustomerRoleMember, Get-PCAddressRulesByMarket, Get-PCAuditRecord...}

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2395
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2395
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Suffice it to say other commands using the same token return values fine. It appears that this API endpoint is just broken.

I am using USER authentication. To be 100% clear.

**Comment by isaiahwilliams** [comment]
Hi @cblackuk,

We have been hard at working developing a new version of this module, that leverages the Partner Center .NET SDK. This change in architecture will allow us to avoid these type of errors and provide more capabilities with less overhead. I do not believe that we have added this particular cmdlet to the new version just yet, but I will piroritize it that way you will be able to switch to the new version as soon as possible. You can find more information about the new version at https://github.com/Microsoft/Partner-Center-PowerShell

**Comment by cblackuk** [comment]
@isaiahwilliams  Thanks a lot, I do believe that the API itself might be broken not just the cmdlet as I tried directly via API and it is the same :-/

**Comment by cblackuk** [comment]
@isaiahwilliams I noticed something interesting in the new module -> New-PartnerCustomerAgreement

I read through the md file provided but I still am struggling to understand what this command really is meant to accomplish.

Do you mind explaining that please?

**Comment by isaiahwilliams** [comment]
Hi @cblackuk, when accessing the customer in Partner Center do you receive an error as well? It is possible that the relationship between this customer and you has been removed. If you do not receive any error when accessing this customer in Partner Center, then I would recommend that you open a support case, so the Microsoft support organization can investigate. 

With respect to the new New-PartnerCustomerAgreement cmdlet, that is for partners to confirm that the customer has accepted the Microsoft Cloud Agreement (MCA). Microsoft recently announced they will be requiring partner's to confirm that both existing and new customers have accepted the MCA. This process is part of a compliance push, so we wanted to make sure that partners had numerous ways for quickly updating this information. You can find more details in Yammer and in the following links 

https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/scenarios/confirm-customer-consent.md
https://docs.microsoft.com/en-us/partner-center/develop/confirm-customer-consent

**Comment by cblackuk** [comment]
Hi @isaiahwilliams  Thanks for getting back to me. No via portal itself I do not get any errors it is only via PShell or API.

As for New-PartnerCustomerAgreement I will take a look at the latter link, the former is what I have read and I still did not get what it is trying to accomplish.

I was hoping it was to automate the reseller request consent on behalf of the customer...

**Comment by isaiahwilliams** [comment]
Hi @cblackuk we will be releasing an update to the new PowerShell module this week. That update will include a command that you can use to obtain the relationship between a partner and a customer. Since you are receiving this error when you are calling the API directly, I would like to encourage you to open a support ticket through Partner Center. That way the Microsoft organization can investigate and address the problem. With respect to this issue I am going to close this issue because our new module will have this feature later this week. Please feel free to re-open this request if you have any additional questions regarding the relationship.

**Comment by cblackuk** [comment]
I will test it out on a new module and we shall see how it goes :-) thanks @isaiahwilliams
