### ISSUE TITLE
Unable to log in with Federated AD Credentials

### ISSUE THREAD

**Issue by PowellDean** [Microsoft/PartnerCenterPowerShellModule#84]
When we supply PartnerCenter credentials to the Add-PCAuthentication routine, we continually receive a "401 Unauthorized" error. We have verified we are entering the credentials correctly. Full error message:

```
Add-PCAuthentication -Credential $creds -CspAppId <appid> -CspDomain <federated domain>

Invoke-RestMethod : {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials.
AADSTS50126: Invalid username or password\r\nTrace ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\r\nCorrelation ID:
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\r\nTimestamp: 2018-08-08
23:08:58Z","error_codes":[70002,50126],"timestamp":"2018-08-08
23:08:58Z","trace_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","correlation_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}
At ...\PartnerCenterModule\0.10.0.4\PartnerCenterAuthentication.psm1:35 char:17
+ ... $response = Invoke-RestMethod -Uri $url -ContentType "application/x-w ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
The property 'access_token' cannot be found on this object. Verify that the property exists.
At ...\PartnerCenterModule\0.10.0.4\PartnerCenterAuthentication.psm1:36 char:12
+     return $response.access_token
+            ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Cannot retrieve the token: The remote server returned an error: (401) Unauthorized.
```

We have an integration sandbox account, and login to this with this module works perfectly. The difference between our sandbox and regular production is that our credentials in production are authenticated against a federated Active Directory.

Does this module work with federated AD accounts? If so, what do we need to do to authenticate these accounts properly?

I have stripped out the trace_id and correlation_id GUIDs, but can supply them if necessary.

Regards,
Dean Powell
Edmonton, Canada

**Comment by isaiahwilliams** [comment]
Hi Dean,

I believe you have discovered one of the limitations with how this module is designed. Recently we published a pre-release version of a new module that will be replacing this one in the coming weeks. Would you mind testing this scenario with https://github.com/Microsoft/Partner-Center-PowerShell and letting me know if you have the same issue?

**Comment by isaiahwilliams** [comment]
Hi @PowellDean I am going to close this issue because of the release of our new Partner Center PowerShell module. If you are experincing the same issue with that module, please open a new issue using the issue tracker associated with that repository.
