### ISSUE TITLE
Get-PCCustomerUser - Return more than 500 users / paging?

### ISSUE THREAD

**Issue by o-l-a-v** [Microsoft/PartnerCenterPowerShellModule#86]
# Feature Request

I'll start by saying that I really appreciate your work with this module.

**Is your feature request related to a problem? Please describe.**
I'm trying to get all users of a customer of ours, but Get-PCCustomerUser can only return maximum of 500 users. How do I get the rest? I can't specify page, or a bigger size.

**Describe the solution you would like**
I'd like to either:
* Specify a bigger ResultSize
* Specify page, so that I can get pages until the result I receive is less than max page size (which would be the normal way of handling this I believe)

**Describe alternatives you have considered**
None so far, should be a easy fix/ addition. I'll write my own module if I have to.

**Additional context**
![image](https://user-images.githubusercontent.com/6450056/44663040-abe5de00-aa0f-11e8-83d8-537846a231af.png)

Maximum for ResultSize (500) is not listed in the documentation BTW
`Get-Help -Name 'Get-PCCustomerUser' -Full`
![image](https://user-images.githubusercontent.com/6450056/44662431-139b2980-aa0e-11e8-8b10-290ce2c93931.png)
* IMO it should be called "PageSize", and there should be a parameter "Page".

**Comment by isaiahwilliams** [comment]
Hi Olav, 

We have developed a new PowerShell module that leverages the Partner Center .NET SDK. This new module has this functionality and numerous others. You can find more information about this module at https://github.com/Microsoft/Partner-Center-PowerShell

Please let me know if you have any issues with the new module.

**Comment by o-l-a-v** [comment]
Thanks, I'll have a look tomorrow.

**Comment by o-l-a-v** [comment]
Got it working, thanks.
So PartnerCenterModule is/ will be deprecated?
