### ISSUE TITLE
Get-PCInvoiceLineItem should support OneTime as BillingProvider

### ISSUE THREAD

**Issue by Agazoth** [Microsoft/PartnerCenterPowerShellModule#87]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Reserved instances have been added to CSP. These are billed as on time fees and have one_time as BillingProvider. The commandlet does not support this BillingProvider

**Describe the solution you would like**
OneTime should be added as Billing Provider and Invoice Line Items should be extracted

**Describe alternatives you have considered**
No alternative

**Additional context**

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, 

Thank you for opening this feature request. This version of the PowerShell has been deprecated and replaced with https://github.com/Microsoft/Partner-Center-PowerShell. The new module has the ability to obtain the invoice line items that you are seeking. You can find more information at https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/Get-PartnerInvoiceLineItem.md

I hope that this helps!

**Comment by Agazoth** [comment]
Excellent! Thank you!
